#!/usr/bin/env bash
# Install the git pre-commit hook that validates the graph before every commit.
#
#   bash scripts/install_hooks.sh
#
# Idempotent. To bypass once (don't make a habit of it): git commit --no-verify

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="$ROOT/.git/hooks/pre-commit"

mkdir -p "$(dirname "$HOOK")"
cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Generated by scripts/install_hooks.sh -- validates the context graph.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

if ! command -v python3 >/dev/null 2>&1; then
  echo "pre-commit: python3 not found, skipping graph validation" >&2
  exit 0
fi

if ! python3 scripts/graph.py validate; then
  echo
  echo "pre-commit: graph validation failed. Fix the errors above, or use --no-verify"
  echo "if you genuinely need to commit a broken graph."
  exit 1
fi

# Generated files must not drift from the graph they came from.
python3 scripts/graph.py index >/dev/null
python3 scripts/build_board.py >/dev/null
if ! git diff --quiet -- generated/; then
  echo
  echo "pre-commit: generated/ was out of date and has been rebuilt."
  echo "Stage it and commit again:  git add generated/"
  exit 1
fi
EOF

chmod +x "$HOOK"
echo "Installed pre-commit hook at .git/hooks/pre-commit"
echo "It runs: graph.py validate, then checks generated/ is current."
